name:  move-decls (comment)
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  run-action:
    #if: contains(github.event.comment.body, 'move-decls')
    runs-on: ubuntu-latest

    steps:
      - id: short_diff
        run: |
          printf $'summary<<EOF\n%s\nEOF' "hello comment" >> "$GITHUB_OUTPUT"
      - name: Add comment
        run: gh pr comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BODY: ${{ steps.short_diff.outputs.summary }}
#on:
#  issue_comment:
#    types: [created, edited]
#  pull_request_review_comment:
#    types: [created, edited]

#jobs:
#  move-decls-add-comment:
#    if: contains(github.event.comment.body, 'move-decls') # || ((github.event.issue.pull_request != 'null') && (startsWith(github.event.comment.body, 'move-decls') || contains(toJSON(github.event.comment.body), '\r\nmove-decls')))
#    runs-on: ubuntu-latest
#    permissions:
#      pull-requests: write
#    steps:
#      - id: short_diff
#        run: |
#          printf $'summary<<EOF\n%s\nEOF' "hello comment" >> "$GITHUB_OUTPUT"
#      - name: Add comment
#        run: gh pr comment "$NUMBER" --body "$BODY"
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GH_REPO: ${{ github.repository }}
#          NUMBER: ${{ github.event.pull_request.number }}
#          BODY: ${{ steps.short_diff.outputs.summary }}
#
